// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMotionChange();

float temperature;
bool motion;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motion, READWRITE, ON_CHANGE, onMotionChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
